### ISSUE TITLE
How to differentiate two phone number views in the delegate methods?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [JNDisrupter/JNPhoneNumberView#25]
I have two phone numbers of views in my app. I want to differentiate which phone number view is user typing in the delegate methods  like below text field delegate methods

```
    func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        if(textField == firsttextfield)
        {
            return true
        }
        
        return true
    }

```

**Comment by jayelzaghmoutt** [comment]
@ArigarasuthanRepo We added phoneNumberView in the delegates as follow:

`func phoneNumberView(didChangeText nationalNumber: String, country: JNCountry, forPhoneNumberView phoneNumberView: JNPhoneNumberView)`
